const ActionType = {
    NAVIGATE: 'NAVIGATE',
    BACK: 'BACK',

    NAVIGATE_REPLACE: "NAVIGATE_REPLACE",
    NAVIGATE_RESET: "NAVIGATE_RESET",

    TOKEN_CHECKING: "TOKEN_CHECKING",
    TOKEN_CHECKING_SUCCESS: "TOKEN_CHECKING_SUCCESS",
    TOKEN_CHECKING_FAIL: "TOKEN_CHECKING_FAIL",

    DASHBOARD_FETCHING: "DASHBOARD_FETCHING",
    DASHBOARD_SUCCESS: "DASHBOARD_SUCCESS",
    DASHBOARD_FAIL: "DASHBOARD_FAIL",

    LOGGING: "LOGGING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    REGISTERING: "REGISTERING",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",

    PACKAGE_FETCHING: "PACKAGE_FETCHING",
    PACKAGE_SUCCESS: "PACKAGE_SUCCESS",
    PACKAGE_FAIL: "PACKAGE_FAIL",

    RESERVATION_SET_PACKAGE: "RESERVATION_SET_PACKAGE",
    RESERVATION_SET_DATE: "RESERVATION_SET_DATE",
    RESERVATION_SET_FORM_DATA: "RESERVATION_SET_FORM_DATA",

    RESERVING: "RESERVING",
    RESERVE_SUCCESS: "RESERVE_SUCCESS",
    RESERVE_FAIL: "RESERVE_FAIL",

    LOGOUT: "LOGOUT",
};

export default ActionType;